# Database Connection
spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Redis Connection
spring.cache.type=${SPRING_CACHE_TYPE}
spring.data.redis.url=${REDIS_URL}

# Logging config
logging.level.root=info
logging.level.io.propertyintel=debug

# Disable JPA auto-schema generation
spring.jpa.hibernate.ddl-auto=none

# Flyway-specific settings
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# OpenAPI config
springdoc.swagger-ui.tags-sorter=alpha

# Security config
accesstoken.expiry.milliseconds=${ACCESSTOKEN_EXPIRY_MILLISECONDS}
accesstoken.expiry.seconds=${ACCESSTOKEN_EXPIRY_SECONDS}
refreshtoken.expiry.seconds=${REFRESHTOKEN_EXPIRY_SECONDS}

# JWT Signing keys
jwt.private-key-path=/app/secrets/private.pem
jwt.public-key-path=/app/secrets/public.pem

# Rate Limiting Config
ratelimit.auth.capacity=${RATELIMIT_AUTH_CAPACITY}
ratelimit.auth.refill.tokens=${RATELIMIT_AUTH_REFILL_TOKENS}
ratelimit.auth.refill.duration=${RATELIMIT_AUTH_REFILL_DURATION}

ratelimit.public.capacity=${RATELIMIT_PUBLIC_CAPACITY}
ratelimit.public.refill.tokens=${RATELIMIT_PUBLIC_REFILL_TOKENS}
ratelimit.public.refill.duration=${RATELIMIT_PUBLIC_REFILL_DURATION}

ratelimit.authenticated.capacity=${RATELIMIT_AUTHENTICATED_CAPACITY}
ratelimit.authenticated.refill.tokens=${RATELIMIT_AUTHENTICATED_REFILL_TOKENS}
ratelimit.authenticated.refill.duration=${RATELIMIT_AUTHENTICATED_REFILL_DURATION}