name: Property Intel CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Temporary JWT Keys for Tests
        run: |
          mkdir -p api/src/main/resources/keys
          openssl genpkey -algorithm RSA -out api/src/main/resources/keys/private.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in api/src/main/resources/keys/private.pem -out api/src/main/resources/keys/public.pem

      - name: Run Integration & Unit Tests
        run: ./mvnw clean test
        working-directory: api

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: api/target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-branches-badge: true

      - name: Commit and push the badge
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'ci: (api) update test coverage badge [skip ci]'
          add: '.github/badges/*.svg'
